name: Deploy para Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Autenticação no Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Configurar SDK do Google Cloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - name: Configurar Docker no Artifact Registry
      run: |
        # Crie o repositório no Artifact Registry caso não exista
        gcloud artifacts repositories create cloud-run-source-deploy \
          --repository-format=docker \
          --location=us-central1 \
          --description="Repositório para imagens do Cloud Run" || true
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build e Push da Imagem Docker
      run: |
        IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/api-ocr:${{ github.sha }}
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy no Cloud Run
      run: |
        IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/api-ocr:${{ github.sha }}
        gcloud run deploy servico-ocr-comercial \
          --image $IMAGE_NAME \
          --region us-central1 \
          --allow-unauthenticated \
          --memory 2Gi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 2 \
          --timeout 300 \
          --set-env-vars GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
